### PR TITLE
fix python 2.7

### PR DESCRIPTION
**Pull request by datphan**
for this https://iorad.slack.com/archives/D01042TBEHG/p1622258901004100

### CODE REVIEW

**Comment by hoatle** [comment]
I can reproduce the problem with teracy-dev-certs v0.5.0 and v0.6.0-SNAPSHOT:

```bash
$ vagrant up
Bringing machine 'node-01' up with 'virtualbox' provider...
==> node-01: Importing base box 'bento/ubuntu-18.04'...
==> node-01: Matching MAC address for NAT networking...
==> node-01: Checking if box 'bento/ubuntu-18.04' version '202010.24.0' is up to date...
==> node-01: Setting the name of the VM: teracy-dev_node-01_1623057096909_7177
==> node-01: Clearing any previously set network interfaces...
==> node-01: Preparing network interfaces based on configuration...
    node-01: Adapter 1: nat
==> node-01: Forwarding ports...
    node-01: 22 (guest) => 2222 (host) (adapter 1)
==> node-01: Running 'pre-boot' VM customizations...
==> node-01: Booting VM...
==> node-01: Waiting for machine to boot. This may take a few minutes...
    node-01: SSH address: 127.0.0.1:2222
    node-01: SSH username: vagrant
    node-01: SSH auth method: private key
    node-01: 
    node-01: Vagrant insecure key detected. Vagrant will automatically replace
    node-01: this with a newly generated keypair for better security.
    node-01: 
    node-01: Inserting generated public key within guest...
    node-01: Removing insecure key from the guest if it's present...
    node-01: Key inserted! Disconnecting and reconnecting using new SSH key...
==> node-01: Machine booted and ready!
==> node-01: Checking for guest additions in VM...
==> node-01: Setting hostname...
==> node-01: Mounting shared folders...
    node-01: /vagrant => /Users/hoatle/teracy-dev
==> node-01: Running provisioner: teracy-dev-certs (ansible_local)...
    node-01: Installing Ansible...
    node-01: Installing pip... (for Ansible installation)
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

curl https://bootstrap.pypa.io/get-pip.py | sudo python

Stdout from the command:

ERROR: This script does not work on Python 2.7 The minimum supported Python version is 3.6. Please use https://bootstrap.pypa.io/pip/2.7/get-pip.py instead.


Stderr from the command:

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1892k  100 1892k    0     0  2104k      0 --:--:-- --:--:-- --:--:-- 2102k

==> node-01: The previous process exited with exit code 1.
```

**Comment by hoatle** [comment]
@datphan I got this error:

```
    node-01: Installing pip... (for Ansible installation)
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

curl https://bootstrap.pypa.io/2.7/get-pip.py | sudo python

Stdout from the command:



Stderr from the command:

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   146  100   146    0     0    247      0 --:--:-- --:--:-- --:--:--   247
  File "<stdin>", line 1
    <html>
    ^
SyntaxError: invalid syntax

==> node-01: The previous process exited with exit code 1.
```

**Review by hoatle — CHANGES_REQUESTED** [review]
please check my comments

**Comment by datphan** [comment]
> please check my comments

fixed, pls check again

**Comment by hoatle** [comment]
thank you, it works now, I'm going to push this hot fix for v0.5.1 release

**Pull request closed without merging**
