### PR TITLE
@ #1 | should support another bento box

### PR DESCRIPTION
**Pull request by hieptranquoc**
connect #1 
please check this PR! Thank you

### CODE REVIEW

**Comment by hieptranquoc** [comment]
I tested with Debian, Fedora, FreeBSD, RedHat, and Ubuntu

**Comment by hoatle** [comment]
@hieptranquoc pls update README for supported guest OSes

**Comment by phuonglm** [comment]
LGTM, code ok, tested.

**Comment by hieptranquoc** [comment]
@hoatle I've updated! Please check this PR again! Thank you

**Pull request merged**
